FROM python:3.12-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    docker.io \
    python3-dev \
    python3-pip \
    curl \
    git \
    python3-setuptools \
    python3-wheel \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel

WORKDIR /app

COPY .. .

RUN pip install --no-cache-dir -r requirements.txt